apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sogos-marketing

resources:
  - namespace.yaml
  - networkpolicy.yaml
  - frontend/deployment.yaml
  - frontend/service.yaml
  - backend/deployment.yaml
  - backend/service.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: sogos-marketing
    includeSelectors: false
